### ISSUE TITLE
🐛 Bug Report: Failed -> kotlin.Unit

### ISSUE THREAD

**Issue by dbsaiz** [iammohdzaki/AabToApk-Desktop#11]
When I push Execute Logs says "Failed -> kotlin.Unit"

![Captura de pantalla 2024-09-16 153747](https://github.com/user-attachments/assets/97dc87ec-1425-4f9c-88bb-a8f5f5123343)

**Comment by iammohdzaki** [comment]
Thank you for sharing the issue. Please share the OS you are using and other details.

**Comment by dbsaiz** [comment]
Hi
Thank you for answer
My OS is W11. Pro 23H2 (22631.4169) [Ryzen 7 5800H]

**Comment by iammohdzaki** [comment]
Is Java also installed and set to home path?

**Comment by dbsaiz** [comment]
I guess the .abb file is presigned with a debug key from My ide

Java is installed but I do not know if it is set to home path...  How can I check that?

**Comment by iammohdzaki** [comment]
It doesn't matter if your aab is presigned bundletool when converting to apk for installation resign it with provided debug or release key.Thats why to use aab Google wants you to upload signing keys.
To check java path try to run cmd and type java .If it works path is set otherwise you will find tutorial to set java path also.

**Comment by dbsaiz** [comment]
0k
Thank you!!
